import { createMockSeed, derivePredictionFromCapture } from "@/lib/mocks/data";
import type {
  CameraCapture,
  MeshNetwork,
  MonitoringEvent,
  PredictionResult,
  TraySystem
} from "@/lib/types/domain";

interface MockStore {
  trays: TraySystem[];
  captures: CameraCapture[];
  predictions: PredictionResult[];
  events: MonitoringEvent[];
  meshes: MeshNetwork[];
  lastRotationAt: number;
}

declare global {
  // eslint-disable-next-line no-var
  var __agrihomeMockStore__: MockStore | undefined;
}

const getGlobalStore = () => {
  if (!globalThis.__agrihomeMockStore__) {
    globalThis.__agrihomeMockStore__ = createMockSeed();
  }

  return globalThis.__agrihomeMockStore__;
};

const rotateSimulation = (store: MockStore) => {
  const now = Date.now();

  if (now - store.lastRotationAt < 60_000) {
    return store;
  }

  const tray = store.trays[now % store.trays.length];
  const capture: CameraCapture = {
    id: `capture-${now}`,
    trayId: tray.id,
    trayName: tray.name,
    deviceId: tray.deviceId,
    imageUrl: `/images/test-image.jpg?v=${now}`,
    capturedAt: new Date(now).toISOString(),
    source: "simulator",
    status: "available",
    notes: "Latest frame generated by the simulation layer."
  };

  const prediction = derivePredictionFromCapture(capture);
  const event: MonitoringEvent = {
    id: `event-${now}`,
    captureId: capture.id,
    trayId: capture.trayId,
    level: prediction.severity === "high" ? "critical" : "info",
    title: "New frame analyzed",
    message: `${capture.trayName} was tagged as ${prediction.label.toLowerCase()} during the latest vector lookup.`,
    createdAt: capture.capturedAt
  };

  store.captures = [capture, ...store.captures].slice(0, 12);
  store.predictions = [prediction, ...store.predictions].slice(0, 12);
  store.events = [event, ...store.events].slice(0, 30);
  store.trays = store.trays.map((item) =>
    item.id === tray.id
      ? {
          ...item,
          healthScore:
            prediction.severity === "high"
              ? Math.max(item.healthScore - 4, 52)
              : Math.min(item.healthScore + 1, 99),
          status:
            prediction.severity === "high"
              ? "alert"
              : prediction.severity === "medium"
                ? "watch"
                : "healthy",
          lastCaptureAt: capture.capturedAt
        }
      : item
  );
  store.lastRotationAt = now;

  return store;
};

export const getMockStore = () => rotateSimulation(getGlobalStore());

export const ingestMockCapture = (capture: CameraCapture) => {
  const store = getGlobalStore();
  const prediction = derivePredictionFromCapture(capture);
  const event: MonitoringEvent = {
    id: `event-${capture.id}`,
    captureId: capture.id,
    trayId: capture.trayId,
    level: "info",
    title: "Hardware ingest received",
    message: `Camera frame from ${capture.trayName} accepted into the staging pipeline.`,
    createdAt: capture.capturedAt
  };

  store.captures = [capture, ...store.captures].slice(0, 12);
  store.predictions = [prediction, ...store.predictions].slice(0, 12);
  store.events = [event, ...store.events].slice(0, 30);
  store.trays = store.trays.map((tray) =>
    tray.id === capture.trayId
      ? {
          ...tray,
          deviceId: capture.deviceId,
          lastCaptureAt: capture.capturedAt
        }
      : tray
  );

  return { capture, prediction };
};

export const createMockMesh = (name: string, trayIds: string[]) => {
  const store = getGlobalStore();
  const mesh: MeshNetwork = {
    id: `mesh-${Date.now()}`,
    name,
    trayIds,
    nodeCount: trayIds.length,
    status: "draft",
    createdAt: new Date().toISOString(),
    summary: `Links ${trayIds.length} tray nodes for shared monitoring, routing, and future hardware coordination.`
  };

  store.meshes = [mesh, ...store.meshes];

  return mesh;
};
