import { MANUAL_TRAY_ID } from "@/lib/constants/manual-tray";
import {
  buildPlantReportFromPrediction,
  createMockSeed,
  derivePredictionFromCapture
} from "@/lib/mocks/data";
import type {
  CameraCapture,
  CaptureSchedule,
  MeshNetwork,
  MonitoringEvent,
  PlantReport,
  PlantUnit,
  PredictionResult,
  TraySystem
} from "@/lib/types/domain";

interface MockStore {
  trays: TraySystem[];
  plants: PlantUnit[];
  captures: CameraCapture[];
  predictions: PredictionResult[];
  reports: PlantReport[];
  events: MonitoringEvent[];
  meshes: MeshNetwork[];
  schedules: CaptureSchedule[];
  lastRotationAt: number;
}

declare global {
  var __agrihomeMockStore__: MockStore | undefined;
}

const getGlobalStore = () => {
  if (!globalThis.__agrihomeMockStore__) {
    globalThis.__agrihomeMockStore__ = createMockSeed();
  }

  return globalThis.__agrihomeMockStore__;
};

/** Writable mock store without running the simulation rotation (for vision / admin updates). */
export const getGlobalMockStore = () => getGlobalStore();

const rotateSimulation = (store: MockStore) => {
  const now = Date.now();

  if (now - store.lastRotationAt < 60_000) {
    return store;
  }

  const tray = store.trays[now % store.trays.length];
  const trayPlants = store.plants.filter((plant) => plant.trayId === tray.id);
  const focusPlant = trayPlants[now % trayPlants.length];

  const capture: CameraCapture = {
    id: `capture-${now}`,
    trayId: tray.id,
    trayName: tray.name,
    deviceId: tray.deviceId,
    imageUrl: `/images/test-image.jpg?v=${now}`,
    capturedAt: new Date(now).toISOString(),
    source: "simulator",
    status: "available",
    notes: "Latest frame generated by the simulation layer."
  };

  const prediction = derivePredictionFromCapture(capture);
  const report: PlantReport = {
    id: `${focusPlant.id}-report-${now}`,
    trayId: tray.id,
    plantId: focusPlant.id,
    captureId: capture.id,
    diagnosis:
      prediction.severity === "high"
        ? "Disease risk detected"
        : prediction.severity === "medium"
          ? "Nutrient deficiency watch"
          : "Healthy growth pattern",
    confidence: prediction.confidence,
    severity: prediction.severity,
    diseases: prediction.severity === "high" ? ["early blight"] : [],
    deficiencies:
      prediction.severity === "medium" ? ["nitrogen deficiency"] : [],
    anomalies:
      prediction.severity === "high"
        ? ["necrotic leaf spotting"]
        : ["minor canopy asymmetry"],
    summary: `Scan of ${focusPlant.name}.`,
    recommendedAction:
      prediction.severity === "high"
        ? "Isolate; re-image today."
        : prediction.severity === "medium"
          ? "Check feed; re-image in 24h."
          : "No change.",
    status: prediction.severity === "high" ? "pending_review" : "ready",
    createdAt: capture.capturedAt
  };

  const event: MonitoringEvent = {
    id: `event-${now}`,
    captureId: capture.id,
    trayId: capture.trayId,
    plantId: focusPlant.id,
    level: prediction.severity === "high" ? "critical" : "info",
    title: "Scan done",
    message: `${focusPlant.name} · ${capture.trayName}`,
    createdAt: capture.capturedAt
  };

  store.captures = [capture, ...store.captures].slice(0, 24);
  store.predictions = [prediction, ...store.predictions].slice(0, 24);
  store.reports = [report, ...store.reports].slice(0, 60);
  store.events = [event, ...store.events].slice(0, 60);
  store.trays = store.trays.map((item) =>
    item.id === tray.id
      ? {
          ...item,
          healthScore:
            prediction.severity === "high"
              ? Math.max(item.healthScore - 3, 52)
              : Math.min(item.healthScore + 1, 99),
          status:
            prediction.severity === "high"
              ? "alert"
              : prediction.severity === "medium"
                ? "watch"
                : "healthy",
          lastCaptureAt: capture.capturedAt
        }
      : item
  );
  store.plants = store.plants.map((item) =>
    item.id === focusPlant.id
      ? {
          ...item,
          healthScore:
            prediction.severity === "high"
              ? Math.max(item.healthScore - 5, 44)
              : prediction.severity === "medium"
                ? Math.max(item.healthScore - 2, 60)
                : Math.min(item.healthScore + 1, 99),
          status:
            prediction.severity === "high"
              ? "alert"
              : prediction.severity === "medium"
                ? "watch"
                : "healthy",
          latestDiagnosis: report.diagnosis,
          lastReportAt: report.createdAt,
          lastImageUrl: capture.imageUrl
            ? `${capture.imageUrl}${capture.imageUrl.includes("?") ? "&" : "?"}plant=${item.id}`
            : item.lastImageUrl,
          lastImageAt: capture.capturedAt
        }
      : item
  );
  store.schedules = store.schedules.map((schedule) =>
    schedule.scopeType === "tray" && schedule.scopeId === tray.id
      ? {
          ...schedule,
          lastRunAt: capture.capturedAt,
          nextRunAt: new Date(
            now + schedule.intervalMinutes * 60 * 1000
          ).toISOString()
        }
      : schedule
  );
  store.lastRotationAt = now;

  return store;
};

export const getMockStore = () => rotateSimulation(getGlobalStore());

export const ensureManualTrayInMockStore = () => {
  const store = getGlobalStore();
  if (store.trays.some((t) => t.id === MANUAL_TRAY_ID)) {
    return;
  }
  store.trays.push({
    id: MANUAL_TRAY_ID,
    name: "My plants",
    zone: "Manual entry",
    crop: "Custom",
    plantCount: 0,
    visionPlantCount: null,
    visionPlantCountAt: null,
    visionPlantCountConfidence: null,
    visionDetections: null,
    healthScore: 92,
    status: "healthy",
    deviceId: "user-device",
    lastCaptureAt: new Date().toISOString()
  });
};

export const createManualPlantInStore = (input: {
  name: string;
  cultivar: string;
  trayId: string;
}): PlantUnit => {
  const store = getMockStore();
  const tray = store.trays.find((t) => t.id === input.trayId);
  if (!tray) {
    throw new Error("Tray not found");
  }
  const siblings = store.plants.filter((p) => p.trayId === input.trayId);
  const n = siblings.length + 1;
  const plant: PlantUnit = {
    id: `plant-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    trayId: input.trayId,
    meshIds: [],
    name: input.name.trim(),
    cultivar: input.cultivar.trim(),
    slotLabel: `M-${n}`,
    row: Math.ceil(n / 3),
    column: ((n - 1) % 3) + 1,
    healthScore: 88,
    status: "healthy",
    lastReportAt: new Date().toISOString(),
    latestDiagnosis: "Awaiting first photo analysis",
    lastImageUrl: null,
    lastImageAt: new Date().toISOString()
  };
  store.plants = [...store.plants, plant];
  store.trays = store.trays.map((t) =>
    t.id === input.trayId ? { ...t, plantCount: t.plantCount + 1 } : t
  );
  return plant;
};

/**
 * Runs simulated CV → report for a capture. Updates in-memory mock store only
 * when this plant exists there (typical when NEXT_PUBLIC_USE_MOCK_DATA=true).
 */
export const finalizePlantPhotoAnalysisForPlant = (
  plant: PlantUnit,
  capture: CameraCapture
): { report: PlantReport; prediction: PredictionResult } => {
  const store = getMockStore();
  let prediction = store.predictions.find((p) => p.captureId === capture.id);
  if (!prediction) {
    prediction = derivePredictionFromCapture(capture);
    store.predictions = [prediction, ...store.predictions].slice(0, 48);
  }
  const report = buildPlantReportFromPrediction(plant, capture, prediction);
  const newHealth =
    prediction.severity === "high"
      ? Math.max(plant.healthScore - 8, 44)
      : prediction.severity === "medium"
        ? Math.max(plant.healthScore - 4, 60)
        : Math.min(plant.healthScore + 2, 98);
  const newStatus: PlantUnit["status"] =
    prediction.severity === "high"
      ? "alert"
      : prediction.severity === "medium"
        ? "watch"
        : "healthy";

  const inMock = store.plants.some((p) => p.id === plant.id);
  if (inMock) {
    store.reports = [report, ...store.reports].slice(0, 80);
    store.plants = store.plants.map((p) =>
      p.id === plant.id
        ? {
            ...p,
            healthScore: newHealth,
            status: newStatus,
            latestDiagnosis: report.diagnosis,
            lastReportAt: report.createdAt,
            lastImageUrl: capture.imageUrl,
            lastImageAt: capture.capturedAt
          }
        : p
    );
    const event: MonitoringEvent = {
      id: `event-${capture.id}-${plant.id}`,
      captureId: capture.id,
      trayId: plant.trayId,
      plantId: plant.id,
      level: prediction.severity === "high" ? "critical" : "info",
      title: "Photo analysis",
      message: `${plant.name} · ${report.diagnosis}`,
      createdAt: capture.capturedAt
    };
    store.events = [event, ...store.events].slice(0, 80);
    store.trays = store.trays.map((t) =>
      t.id === plant.trayId
        ? {
            ...t,
            lastCaptureAt: capture.capturedAt,
            healthScore: Math.min(
              99,
              Math.round((t.healthScore * 2 + newHealth) / 3)
            )
          }
        : t
    );
  }

  return { report, prediction };
};

export const ingestMockCapture = (capture: CameraCapture) => {
  const store = getGlobalStore();
  const prediction = derivePredictionFromCapture(capture);
  const event: MonitoringEvent = {
    id: `event-${capture.id}`,
    captureId: capture.id,
    trayId: capture.trayId,
    level: "info",
    title: "Frame received",
    message: capture.trayName,
    createdAt: capture.capturedAt
  };

  store.captures = [capture, ...store.captures].slice(0, 24);
  store.predictions = [prediction, ...store.predictions].slice(0, 24);
  store.events = [event, ...store.events].slice(0, 60);
  store.trays = store.trays.map((tray) =>
    tray.id === capture.trayId
      ? {
          ...tray,
          deviceId: capture.deviceId,
          lastCaptureAt: capture.capturedAt
        }
      : tray
  );

  return { capture, prediction };
};

export const createMockMesh = (name: string, trayIds: string[]) => {
  const store = getGlobalStore();
  const mesh: MeshNetwork = {
    id: `mesh-${Date.now()}`,
    name,
    trayIds,
    nodeCount: trayIds.length,
    status: "draft",
    createdAt: new Date().toISOString(),
    summary: `${trayIds.length} trays in this group.`
  };

  store.meshes = [mesh, ...store.meshes];
  store.plants = store.plants.map((plant) =>
    trayIds.includes(plant.trayId)
      ? { ...plant, meshIds: Array.from(new Set([mesh.id, ...plant.meshIds])) }
      : plant
  );

  return mesh;
};

export const upsertMockSchedule = (payload: {
  id?: string;
  scopeType: CaptureSchedule["scopeType"];
  scopeId: string;
  name: string;
  intervalMinutes: number;
  active: boolean;
}) => {
  const store = getGlobalStore();
  const nextSchedule: CaptureSchedule = {
    id: payload.id ?? `schedule-${Date.now()}`,
    scopeType: payload.scopeType,
    scopeId: payload.scopeId,
    name: payload.name,
    intervalMinutes: payload.intervalMinutes,
    active: payload.active,
    destination: "computer-vision-backend",
    lastRunAt: payload.id
      ? store.schedules.find((item) => item.id === payload.id)?.lastRunAt
      : undefined,
    nextRunAt: new Date(
      Date.now() + payload.intervalMinutes * 60 * 1000
    ).toISOString()
  };

  const exists = store.schedules.some((item) => item.id === nextSchedule.id);
  store.schedules = exists
    ? store.schedules.map((item) =>
        item.id === nextSchedule.id ? nextSchedule : item
      )
    : [nextSchedule, ...store.schedules];

  return nextSchedule;
};
